---
language: python
python:
- '2.7'
script: python example/manage.py test billing --settings=settings.travis
install: pip install -i https://simple.crate.io -r example/requirements.txt
env:
  global:
  - secure: ! 'Ymr8xbMv9QdY3GHYv5Xaj8S92DUjOuK9xy7id7KtW4x/fSOUp0kIxbHAynkx

      v3L8FC7F+0sLrcKl3h+tOfq8RZ9eDdqU+Rdbj1YWgQHmLNvzcbDUxomJLq4T

      6ipTR+3NdPuJR5RoH+IN3wXnHIH8akws9FndTeHxcVNEhFiNe/Y='
  - secure: ! 'KyZRC1m/0Vb4nmxDTyBq71FLKsSyCPbGn9i2edFstHAcipxCjOKsIsQq8dfs

      JzU5k2m7SVhI2oOhNfcnJEYAmLiIM89j7ZbELdVMMhPVTF5L3bx1Adr0ZKR+

      oBTYGcXfnriXObxzfdgcqN77CGWTlvXOycw0ZvTOJXN6yjTRLCE='
  - secure: ! 'b7sjSMyxz7tipTZJXKv6CLfDpjWOWNis/YqDR3Vf4wt9NznS50J/I/dPNnqc

      DNwfbCmriQjJJc/itv9VwDYTRA/OFPtSi0Q9jMlRLfH537zt7IXkC16xpJO4

      or2KapoSkosiM2E/8ZNBG3B3ogyLglKR32ctfGhti2hz7kjRJdI='
  - secure: ! 'h7kVNJuC1bA65RDOskucz1fk8uQL3OG8ZjpUscUF3XrPwKCl0fIW0kUgDwrc

      PafOA3JxC6LPhEhDkKOwUBOGUCbpwBU+wfMUMa54ZfwIJYLuBV39naC6m2Sr

      MdRnerzMYJhxyT/Bnxx3O6ceS4wZamYDp+IvqUhAJT8a9pF9zdE='
  - secure: ! 'EZLVSEWKt/l0u1ejG+QYFA6NHOpn05YOEV6q9KqDEVkV4Z8dVQlwlyW3iKtI

      hF3QBAbfZHmgo1z6IFLdJ9qnifyvTY09n8Y1e9oIgUmupvI/fcPOEsvaGUE/

      qOllbscvs2ScQ6VTUGOw3RvgqaO2ITjtU6N3RXBPzdfW7TM8MTs='
  - secure: ! 'E1wWK+DJq+IybnALX58hLHbjYK4eGvGKbEarPA6eb3A0W8+c+nW9ZIQPtE0q

      h1wAUmpBA/5U4F6b+/uRlSWZPZtT1NNP80mW/cY0Rj88albZPAdd+4aUCXg8

      kgsBxZ90aJmLuoMga3iQfh4prlM20TzXueO0jDI+O8drah+i+oM='
  - secure: ! 'YPsprnKxX57ao0e5Qqh4TmL673nQX4HkGg0m+PMvecKbS5g1nR9JzR24SmYG

      hn22fVPihDHMEOHtpVvfvgx1mN3eaWh69iwbXgrd7wmmj907Ri4Piq3oNtBA

      Sb6ogRVGUybrbl2HZ07d+hotnJ9QRxePFYfUU4rpGwHBirfp7uk='
  - secure: ! 'BomUWViHS8NkSzoGWntPHmIlat1iwpLDXTb0L+7L5OK/+Q8vczaVvsJFNVL1

      DgNyipuNMv4yGPd6p8gURYv4rQsZ46MDqzOtzhUXB1qFkqcdgTbN2RxO4ikV

      N6oztNktgEe5SxhYyYhmJqlQ/RqlM1ETSqCOi3HgJS8Y3aj4GWI='
  - secure: ! 'aDdgpSF/D8Yln0X10fk0dVBnh2+XJizuYx8Bc6j8MVP3gVLXWJ3MvErndjcM

      XY5bALhmQdHVhHcSHQnPNk7VkMrvQu6LxxpWui1/dRBsbw7TpZKgkdjFj7R2

      MABED13IhkxcllccqysYlcVpw9lAntsumL5mgazTH+IrHlImwQQ='
  - secure: ! 'FmLiATwUPOYMrTBMSym+AdEAy7QJPerK5siPzNwpVZ9sKmeYzntaUMESWrsT

      3/fGUywuyd+tw3ZbUWpDJmNOZOYBp347UkaHco3DUdqj1dxgSj0wEXdliaPF

      OA2LJRCvP2wJoc+giub+EjBKDYOPmA/vYxV2z2ocH5vuTGym/IY='
  - secure: ! 'dzAZRnL2Z+nR1Vn654/sH8FKP08x8uJstntLfijN4TmD/zhep/Tz48KCgfIi

      l4uR037TqlcdwLl0ldyv89s+I3KxqQKJkR1NPaoKkvXckbrMCWyB+Dm2X1A4

      9DwljYR9XtgcNv6FZ4Zlc2kYKXuGyAoj+2icbUdQh00JnC7qIdg='
  - secure: ! 'ZJUl7bVGLenLTP+zlB59TYnYB+joLfWLhRDcHRiTdHOL8SJFvFyQTYf3P2ik

      0k5LBlCqz7TGuEhoIO48IgX1CVEgMh2vGTGrhMUZ/IwoLAUlWq9cQWn2Imsq

      LOZwQaI/lxTAd0wB+6M6tmw80fwUMhJgtgQNshbQtUydb9j9VKM='
  - secure: ! 'gLHrZ5a0LXI4v4PJscqIBVYEd0V4efRJBvQOfjlVl/j/1Kwu8Pq90XbEssfU

      1dmahsiuFCF6LvAQHXggxPM1PevxCngvn8SuYbx8X4l7a7nFX33gXO6nWZtl

      y83M51H85ompL8vA1XPgIb8WxTvE/DhA6/lSAf3AYkg2btwZ0aA='
  - secure: ! 'Kh09WAf1nd0iNaSyWfEUF7gAxZvjWZ5Sa6yxIwvA345a9k3OpJcHl3+oubjk

      +ioEkvY+MvdO2a6l251Sqn7HN8w+9EM7AJTrz6mE/s/6911xTPcNnDZiqQT2

      4DQHJxMds7/ZWiNOZxuZIeRKtG0DOMIpYv5KDhk8OAjDMj6hXsE='
  - secure: ! 'bJanHr8TfuAkQzhRKAW7YVN5v66+vZkWLoFm0rTwe5sv9eXHZIhL6ZfeaqYM

      Zia8lnk6sXvYGfVjtmk9KZpRdXAaAp4aUstggJyVSIsMTiX1fvL7I5ONhlWR

      pNcpEsml6zzOwWLS1mVTMDPtVsAM9pGO4pu67hsOdjnr6JUyCnA='
  - secure: ! 'Qq4I/3961yEMS+OKBBv+AyERnaDTX+RZ+guWFR172/Gm9zlFcZxbvOosyhgz

      pvwUq/2msp9LNXdi8TXIcM9YHJlcV8X8u/QOeCiQCXb//yiQvE0P2YFgWXiP

      QwAjYVvnMtFAppqjPpeD5khJ5jdLjj1Z6o/E++I18jIh/XYGoNA='
  - secure: ! 'gevtTGB19EqAWFH3PNy7KsoY8j/bH20jPwseGGPgjHSOV6i/zpZ/VTZ56ycd

      y1G68EXlf6MBMF18m2w4oG6YZYltXfQ/02uCykftkiWA9gFkbqAUG/TqcfUn

      halnoalQHQc5zGXN/PGgyGccGDl4wqOiIcMH/R2LmoaNJgzBGtI='
  - secure: ! 'QFSn0mBuv+sBAk42DfeQ76tA5y5FUmks46sPojdcVfx8Z98oSMQq/8/w7LaZ

      +WTelMoCxG7a6WM7jxNjRlGSus5VqRTdpT2YqDIEMrKrU6AKIIX0DB7N7lR7

      D6Z6TvtOLkZKe6sG4cMtnls2fncqwe0R8ayp4fB8K6Ywb1olP9g='
  - secure: ! 'fMbv2rpVKr9KpFu613RcmFUH+1zyqB9XY4H+rlEDp5esHsJSmrXrktpQIHST

      LwG+mVA/pJYQEuEC2oxQFME8n/9/zCCNDjuyOMqhlg23flzNYbiq+g5Vl9I4

      x4qJXAkMOXCn0jbAmOFK3TME/FqezJNwXo08YZp//rgdt5SRC6A='
  - secure: ! 'Ms2B7MRYwumPuTYuYxlz8B2LZpbkOfhD2j3D2R14ZCVcotcTkc5iEXgYiWr+

      UIvnD3HwdxrT/cGlSEeyWxseb9MhfZFuYmiiF9kkViP7w+qJ3lJirVFTYfsn

      ouLPhHz3Un9Ck9XD0tA1IYBkDUObrDBOZCEWmwsMM/e6YCLE+3E='
  - secure: ! 'Upfq+sZBs277xYTvyLivAJm+7pBe1W/oC5OGuWGuYMhAnF3QwDtahIE8unbO

      aWcswRWD1CncGiOCXCkEow4BEDymKfp2Qv55/OzlRMEi50cC77ujOQxyza0Y

      8dIqjnM9ju/tv1M/EYnN1cQQRh+VHmnEnKFJC9SOqj7u/u2NOUM='
  - secure: ! 'cTJbHqPB6Q5FG566aRRRKBWYUud2q59HWArD86s0NOUloQ5jgbruIZt/OzDJ

      D+aER6jmn2cCAdq1sk9B1H0zINTSJHY9aymbVGn1cr/N+009m8t2SeKM37lT

      bI1FfUWbnLkv0Lb/sRQgNMx4gJq/VmR6s5lpWYNT4rZZl6ViFlM='
  - secure: ! 'dZ/59HxG3XOqcSMbgR4fk9jXUBfUH/LPMptL2m4aNguut5I3BwV/WZAgYIsp

      NL3xR6OG9WXxGdu2E65l/oorIjdQTX+jFtbp3+UPAp+uxQvAMnbONltGWzxp

      Y4h+tS78ASj++4RirU49qegDH8SwEQRcr/leZEi3l7imktqWkHw='
  - secure: ! 'efw6wJqsc302kKXAUJ3+EGS1kL6+ghdD84KOlbSVMAKhlT+jhEaEQVyh6rHZ

      D5XqgqXIAc/Zlyjs+cINIQnRAsrr7cInev8ftBMJdz3XtxWi2LTNDJf2BrWe

      ffe5A5zwLwTjJ+3nPu9ZwuesV0Kzs84aekZj4QI+w+CniwHlOic='
  - secure: ! 'YnETKbjkMj3kBugimG+4ReuYlZklEGijTnatpQUarSdflY4vf9L97H1klBP2

      5tLWJSydq6418iPjYixUbCfy0h9+Y/cHSdE35lyDaCQ+6MO0YHjD/g8SBauM

      iaHe/GIxokMvsZ6aJMX2689bMB2T6PmL9DbFu4qe9QqVGfeENfQ='
  - secure: ! 'DRr9pLGE8EPHEdLt9Ykr6bU9RKEotDtd3jee9yXA3D7wN9m8HHC5BDCaa31U

      i9k9bcwxEwumfPscuP2HKsKSmHhGgdA28g+aUY/td2YIxpsuwT7+0UmAl89U

      vRe375G8jjgr0cA348xeqaG/oOZAdYihbC7c68hsXBk94PL7CR8='
  - secure: ! 'GZppudo7Qboc9NJG5tDJNdRdmpjCNtiG3VAVryGj9HSRk7Mu1jw7lFB5M6iR

      z5vglTAhZ5lhxNGLa9Om8IBcCOtFqENZ85NS9guJ+xO52pcRiOzmpHPB0Aee

      kO8axv6w5yQG4y7GQ3119PeGT3Y5lybPRlGMljiGuu2B0/g+Tis='
  - secure: ! 'FzOIxDxcEyq8O332vMoypKXCDJKZP1dAPf96Oc4NmKmOFuThfJ3TObEmnJ9m

      U5gIpgOkQ5TDquX2mAsyWylJ+vDn4D0k3RdyitkxGuVlguxzXcSnoMxNn4dD

      rs1jsecW/Sfb5CE8e37jCfUeD9xA7GCEvUeT4ENv0L+F1WwE47s='
  - secure: ! 'I+giVHLdmofkxuX8s7Fcax9dsc6xb7NHlEmtEk4MflzC/+nE6WZsMs/lTzzM

      Ce8YQN0lxjlSYLNZHa6R62lSxrOTfcUr6b+OvWhfssMl1mKV+mLcSNXRpPVk

      x3/5Qf47Jjja6T9wD8aPbmzbTs7DnlglUrw4hmVBb0DwPBDlDRU='
  - secure: ! 'WWfusBrrqNm7t3ZCI2VAl97QKhD4NdKsXIGzMP3IGsHv5OFHJTsqW89hsabo

      XjI+ytrHRnrLBtIfodINxnhwx24qMP6KwZPj0rfw8zrNU5NO9c5yR6198BoO

      qeMgKWPsyP1N/FlXsWT9F8mZcUAeMsIeEjqe8AutUgcv2E/Y0G0='
  - secure: ! 'E8EiggCAORVVmFnKjjk8B13GTjKQVf4VjqL5GR/YnEXfCDsBvPzHFuiQfnmR

      IyAJS3GPraQbqrdvhYjSNcebl2q6BGAdPtZyP6EFTHnmMZZzwfedb0WI64uq

      iz3H+yH11iRYWJ1xOotc4ELbAh5Yqi4uE5CmP0hBz8YTMOIQHSM='
  - secure: ! 'EEKjaGJjx6RwZUgWyBMl+fZfp6vKXzZMTu1sRO7TOUH9tQ3+DoP/7dLGpfIt

      tYcHL57wAYakaWBv5lz/911HUHr9LBGmCTWWutZtmVPhV0ojjEFOcv9IWBQE

      MV3eVI4dYZbUYwi1j9WMd0j7qFcH9iIIRtfEQ2haxIZngb4ycac='
  - secure: ! 'N6/g8b6ioxZ1IFnJ4pC5YwShfhvxxggIKHMJSUBTlMS0l36kfpSztQOPYIyb

      E52IQzmX/vSWU85FoXIm5EqN7NVkNEXY2wa4nJGY+xsnH+M9WPRriELfKwgc

      rey3sYBV6TntjMWKkjI4LrystphgJAfb3Zcut/LwXbvRFO0JvVE='
  - secure: ! 'Ltrpjz7SX1aaXxfe3jzDtVplu0dEYNlwqcVcZgLMjYqWZgy71XQ01bP7FWLY

      NiOkbJ+huy9NsV5qIurQeuQubmTDYzURlVx2RAWt/2xvyW8omNGurGpM89k1

      tZjrrB2cj3GdnSQ0IgcdZCdEfkLQuDlMOu3s4WZl3oTA/jfUVfA='
  - secure: ! 'i4yI9eomdAAWRqsfsPYz6lWxiB275ZMbvG6axyTMmyAOI6+R3pg0CcTqXHsr

      hudTXSGmptO25yfcmQ4PtHVma1N/QY85JB1lpC/YdKEkktJClj/CqOJsT7mz

      o/DTBuTiH9Zq9lvzFuZ9PzN7pzuLWfUsd2YvmmJlQkDsyvPCGMc='
  - secure: ! 'lFnHM+1L47IxmR+nAIbS0Va7iRnPE9PRgvB/C/J0wy4BGhAJE94oxnouIITN

      /oyHYhLjPALr3XAQwo7KkEM7RelC7vc1XYFiWhlE92eK995L0Hruxx/xMQnO

      Tt5LE9kqdsHyev+bZ+7lN6yeSca+sMMbrAH61ZXO37REr9mcxl4='
  - secure: ! 'YOZLnDZT17ldRe6cr1OyAM1NqnAldO7JP723f64KU0kMfRlP8I61YYx6pgUy

      k2mVn9SZZxdW5HmhbItZq0UIUUTVv7nsdk6W8OsoVy8N7vY7+qMu+JQ3wke2

      vclmVP3dWqp65X8N6BF9hnBX3NivHf1qMAs29BHw3Ja/lJ444Zk='
  - secure: ! 'j1IWPF3THuDymPCa2bZVldofQHCu0R0uH+cibk6Ah//NrZm+53wMFDty9Huq

      FPp3C8y0zYE1BuxNcMkn1wR62RS9A/D51YzVXp960JMTLldzQYEMIPcHYjtS

      L19BQGenOi/a7aRS8Ng8GnH19q7NT65ccr8uxzzGBRli9IfM71Y='
  - secure: ! 'HjpAdx7pdKXEIQqJXPzk0jq/Kl/YrYVPZc3kphAxzlWfCDTSxtvCa13XuMw5

      fara3l5/7sfKuaxhhazOx6S+ICwA3BKBJSkLixbxF/gzFw56pt5wQ9gphGem

      CGykfwJdVeDWF8NnC+4Oe6Hq+h3BAgI0fjIYxP/Jwkx3zQnCHWs='
  - secure: ! 'IwjYuLTid9kduJpcrr6Ke37l3hGagRLpRiITva47muj2Z021jgOsCuBa3Z+o

      EGGPhbs5qrLeinPgMnR0/LwyqMnCHSSaLkbq0yBm7Tid7pP68FNqHSDGWIiE

      cu+iF1JENF48R9GHYeIK0aM/f5MMaBGm71TYlZ5UBNIsWuCjlW4='
  - secure: ! 'X+kDm+34IoNgio8R8fQtgjb9BDgQyy/MZaFuSrAl7Z1y/hwoWibmlEgYErLi

      IUvub42IDDb41IQx8HzZL6jPUplaQFJGslYqFqBN17dYjFpPzRXCGtugqX3K

      ymOrO4EQKPa5l2mpqSDsyDoLjon+fDXuCC9KWLoBz7TiyJoT0Kc='
  - secure: ! 'XMb1SnRA2juPlhIy+5JaE3wZQU5KpxlMFg+7mVCnotqjbD01c2a/hoC3C3o8

      fUJTiMK9QRrzwtzmobla6JPFPT9vJ8JayXWLpMKVhYMb3VX1jt999hS1+rYE

      BG1VN8upIKknjtib90x6wddfFTNYUyJdl40dqmhh199LCHDv2q0='
  - secure: ! 'boXoqI+YWdvUmuwjSkw69qmX7yhN2Q+bZgKW+jkCxrLer1T7NPwvlXRgluwy

      Y2/9QkknG0BOGgEdp1vq1q1VBHDaE4PjgaVJ4d9wWyVWa1sf8b1ZPZHm1072

      b+LsyUZNv+wM+8s7iC3QcCxI6Xm0/Vp5NjCQI8JdQxJ9ODarZAM='
  - secure: ! 'hUzgvXVmcb0+T9hxl5foDSYwvDfpbwl9DFDeGYGFlxZZr9ybJltfrE1Ix4Zh

      EwY+XC4YalBSPbXidZea+6MZVHeaxvOxJf5JJlKZncLl5HZkiItaM6AuauPa

      66gzr3HjLM565mSO3X+wRah3RL/MgQSrJp6XmRsCjxDubWGstyc='
  - secure: ! 'Q+iLQPf3JK4l+UC3bxXAGpDgi81EVReLT/26Ge3qMJ2RAfFPJ6Dp4yYAvuZK

      Fl8/tkCIkuM3eQsgs722TPbEoA/SIU860p/F7rsWlOJswRTzDVvOPAj0yp7O

      VblXWT4vbAUU2QdhkO7brXZQj5WMXvKMN0xaV/Ya1BxWvoSp5as='
  - secure: ! 'N6AkUgkQnnW3UzZR6jBxbDutHi+wgc5GwYPh+4yAja9zKzSlxaiODaQKPaEH

      GLv7kcXKboO6zfCcsWuJxwm4AdYOEeQfnqEGPKthMVue3EaaZ8no0l20IWg4

      9j/3ubDi5e+w2+XF89daRrUaCWDk+a8yDphAxgUVxUgJO8r/X1c='
  - secure: ! 'KXJPIObWR8J091qTy+jSPTHLIv4eYuP0+8eKB+KqVkRPGyH0g5B94kTVp888

      jGFCYLaqQbdNJXCt1BC7lqg6KZShZmiiPwgbXmi+x2KI3BUNMYkeyPmI9W3j

      BW9zoVxnB2KFYemRS2F7zbYOc02q6hjZ+01SNwd79T5ltN8SiRo='
  - secure: ! 'PMb7u8haWYfXrX33qTiQsxCnp2u0whApn3sgu7DbZH908N+jQzAWPPcOZnO+

      +ZZXTrM3y549oqpw3nc4/Q/4CFtwAvsQkbzciTQn9qqqhDObKtoAqt7WI4yx

      AlONef2vjBIBCTieqQ5IkqInzD/04GwbFnaDKl6uhU2Rb42iBuw='
  - secure: ! 'VH6csiySUe5d2gzHRb/N84OCCN1cm/UzQnY1A2xSSssIncfrSX9iOSndv6sF

      yr6Wd5y4przZlumoa09UFKO+2SJRDlGH4706qSsoCHnKgQSc8GWA2uVZqOpT

      Yp0J+3j1p+V0yDWkEdL0uaxBnGutCMIheKur5v8kLQKl+Bkat3Q='
  - secure: ! 'G0niunizJ0pWHNfnzVp5uo/rtqqXXMb/DK6tzm59PVGf8mCl/WzOYEDmpeSQ

      kybt6IY5nG7Dekyj0sn01KW8YOjoPzq/A4pQQirwyqxfYMeu4y7BJ2HpCKR5

      E0vg24OZbXLwsdrM6Q2GC2pVjcFG1lkmhOgeDBxJMOGRrR3oieM='
  - secure: ! 'Tn+ipP2WfvgQWbaEWSajqmP0aj8Tet8Ry+pp6+XWsBNejNxf8i8amR3A/CV0

      Y+DLOaFYgmmIt7Ng8oM+J4/rnoqBvXcjwhUdaSrH+PAm5jf87oa9yjDMEAd0

      CwbFKPKr9UIEFzkij0xWP0f9RCZ8vnSEF7cjozbGSdo5lGCO5C4='
  - secure: ! 'QMWubf7q69VEGQcm7Q7fcNgBW9RxTWYvtcDNtVthRRvWonrSxxcC03a2AZLf

      0HlfjaynbMNyd0RFtKUvwraQYg7kIdaIpAuAYn9kZYUlhYAIiCUYB76Xfr0L

      4Jfa0iGcPLLcsdSWJm6hZrGCEwxg2UjCk0AI+TIQsiZEdshSEV0='
  - secure: ! 'BYixiTB+PnzFfeBzDebISGID0Ulzx+JU+TN8EAKbMnAQmBcanqYM6YOCdOOC

      Xc+xjKm6+VYzVj/m6z4riwFdMkbmP4XQNLLq93F6ZsvZ5ywBww/qGMiZlDDc

      wBKa5OONkYmqE0tbp5+yeJTubTpRU5g8TUcOYQ8xjD7bP/WKU4U='
  - secure: ! 'lCrQaPWLqh9kv0XSkRZghy6t7lt8EEaJJffzvcCyezghxNU3e/A/tQHUK5z8

      KA8ZS8MTzB38QV9G2Z+XYf/CdWsfn8hmlhwi9LA3KDPewzILgWlNSPG+uphe

      TOSBrrZ4VowagU/NhypzQpY9MonCY/raYgUTwvNxhaWztVoDQa4='
